Boletto/BE

- src/main/java/com/demoboletto/controller/TravelController.java
- src/main/java/com/demoboletto/domain/Travel.java
- src/main/java/com/demoboletto/dto/request/UpdateTravelDto.java
- src/main/java/com/demoboletto/repository/UserTravelRepository.java
- src/main/java/com/demoboletto/service/TravelService.java
- src/main/java/com/demoboletto/type/ESticker.java
> feat: add updaet&delete travel api

- src/main/java/com/demoboletto/controller/FriendController.java
- src/main/java/com/demoboletto/domain/Friend.java
- src/main/java/com/demoboletto/dto/request/FriendRequestDto.java
- src/main/java/com/demoboletto/dto/response/FriendResponseDto.java
- src/main/java/com/demoboletto/repository/FriendRepository.java
- src/main/java/com/demoboletto/service/FriendService.java
- src/main/java/com/demoboletto/type/EFriendType.java
- 친구 추가
- 유저의 친구 목록 조회
- 특정 친구 키워드 검색
- 특정 친구 삭제
<br/>
- swagger 정리
<br/>
> ✨ feat: add  & get & search & delete friend

- build.gradle
- src/main/java/com/demoboletto/controller/UserController.java
- src/test/java/com/demoboletto/BolettoApplicationTests.java
> 🐛 fix: build error

- src/main/java/com/demoboletto/controller/FriendController.java
- src/main/java/com/demoboletto/domain/Friend.java
- src/main/java/com/demoboletto/dto/request/FriendRequestDto.java
- src/main/java/com/demoboletto/service/FriendService.java
- 여행 친구 추가 부분에서 발생하는  에러를 해결합니다
-
<br/>
> 🐛 fix: Friend Api  Error

- src/main/java/com/demoboletto/constants/Constants.java
- src/main/java/com/demoboletto/controller/FriendController.java
- src/main/java/com/demoboletto/domain/User.java
- src/main/java/com/demoboletto/dto/request/UserProfileUpdateDto.java
- src/main/java/com/demoboletto/dto/response/AddFriendResponseDto.java
- src/main/java/com/demoboletto/service/FriendService.java
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: auth url & response type

- src/main/java/com/demoboletto/controller/AuthController.java
- src/main/java/com/demoboletto/service/AppleService.java
- redirect url을 삭제하고 클라이언트 사이드 로그인을 진행합니다.
> fix: remove redirect url

- src/main/java/com/demoboletto/controller/OAuthController.java
- refreshToken으로 액세스 토큰을 재발급 받는 API 추가
<br/>
> feat: reissue RefreshToken

- src/main/java/com/demoboletto/dto/response/JwtTokenDto.java
- src/main/java/com/demoboletto/utility/JwtUtil.java
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> fix: res userId when login

- src/main/resources/apple-app-site-association
> ✨ feat: universal link configuration

- src/main/java/com/demoboletto/controller/OAuthController.java
- src/main/java/com/demoboletto/domain/Collect.java
- src/main/java/com/demoboletto/domain/User.java
- src/main/java/com/demoboletto/exception/ErrorCode.java
- src/main/java/com/demoboletto/service/KakaoService.java
- src/main/java/com/demoboletto/service/UserService.java
- src/main/java/com/demoboletto/type/ERole.java
- 유저의 회원 탈퇴시 유저 삭제를 soft Delete로 변경합니다.
- 데모 이후 스케줄링 추가
> ✨ feat: Change User sign-out into soft delete

- src/main/java/com/demoboletto/dto/response/JwtTokenDto.java
- src/main/java/com/demoboletto/service/AppleService.java
- src/main/java/com/demoboletto/service/KakaoService.java
> ✨ feat: add log when first login

- src/main/java/com/demoboletto/domain/Picture.java
- src/main/java/com/demoboletto/repository/CollectRepository.java
- src/main/java/com/demoboletto/repository/FriendRepository.java
- src/main/java/com/demoboletto/repository/PictureRepository.java
- src/main/java/com/demoboletto/repository/UserTravelRepository.java
- src/main/java/com/demoboletto/service/KakaoService.java
- src/main/java/com/demoboletto/service/PictureService.java
- src/main/java/com/demoboletto/service/UserService.java
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> feat: hard delete

- src/main/java/com/demoboletto/controller/UserController.java
- src/main/java/com/demoboletto/domain/User.java
- src/main/java/com/demoboletto/dto/request/UserProfileUpdateDto.java
- src/main/java/com/demoboletto/dto/response/GetUserProfileUpdateDto.java
- src/main/java/com/demoboletto/service/CollectService.java
- src/main/java/com/demoboletto/service/UserService.java
- 프레임 & 스티커 조회시 아이디 같이 반환
- 유저 프로필 업데이트 시 반환값 수정
> fix: User Profile Update & get Sticker and Frame 

- src/main/java/com/demoboletto/domain/AlarmSettings.java
- src/main/java/com/demoboletto/dto/response/GetUserProfileUpdateDto.java
- src/main/java/com/demoboletto/service/UserService.java
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> ✨ feat: Alarm Setting

- src/main/java/com/demoboletto/controller/UserController.java
> fix: collect repsonsebody

- src/main/java/com/demoboletto/controller/UserController.java
- src/main/java/com/demoboletto/service/UserService.java
> ✨ feat: get All User Info

- src/main/java/com/demoboletto/dto/response/GetAllUserResponseDto.java
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> feat: GetAllUserInfo

- src/main/java/com/demoboletto/controller/FriendController.java
- src/main/java/com/demoboletto/dto/request/FriendRequestDto.java
- src/main/java/com/demoboletto/dto/response/AddFriendResponseDto.java
- src/main/java/com/demoboletto/repository/FriendRepository.java
- src/main/java/com/demoboletto/service/FriendService.java
- src/main/java/com/demoboletto/service/UserService.java
> fix: Friend Request & Response Body

- src/main/java/com/demoboletto/controller/UserController.java
- src/main/java/com/demoboletto/domain/Travel.java
- src/main/java/com/demoboletto/domain/User.java
- src/main/java/com/demoboletto/service/TravelService.java
- 여행 추가 member 존재시 뜨는 NullPointException 해결
- 프로필 업데이트시 프로필 null값 허용
> fix: request body & NullPointException

- .gitignore
- build.gradle
- src/main/java/com/demoboletto/config/FCMConfig.java
- src/main/java/com/demoboletto/dto/request/OauthLoginDto.java
- src/main/java/com/demoboletto/service/KakaoService.java
> feat: add FCM Configuration

- .gitignore
- src/main/java/com/demoboletto/config/FCMConfig.java
- src/main/java/com/demoboletto/controller/OAuthController.java
- src/main/java/com/demoboletto/domain/User.java
- src/main/java/com/demoboletto/dto/request/AppleLoginDto.java
- src/main/java/com/demoboletto/dto/request/AuthSignUpDto.java
- src/main/java/com/demoboletto/service/AlarmService.java
- src/main/java/com/demoboletto/service/AppleService.java
- src/main/java/com/demoboletto/service/FCMService.java
- src/main/java/com/demoboletto/service/KakaoService.java
- src/main/java/com/demoboletto/service/TravelService.java
- src/main/java/com/demoboletto/type/EAlarmType.java
- src/main/resources/apple-app-site-association
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
> feat: Alarm Service

- src/main/java/com/demoboletto/components/EntityManagerProvider.java
- src/main/java/com/demoboletto/controller/OAuthController.java
- src/main/java/com/demoboletto/controller/UserController.java
- src/main/java/com/demoboletto/domain/SysFrame.java
- src/main/java/com/demoboletto/domain/TravelMemory.java
- src/main/java/com/demoboletto/domain/UserCustomFrame.java
- src/main/java/com/demoboletto/domain/UserFrame.java
- src/main/java/com/demoboletto/domain/common/Frame.java
- src/main/java/com/demoboletto/dto/response/GetUserUsableFrameDto.java
- src/main/java/com/demoboletto/dto/response/TravelMemoryDto.java
- src/main/java/com/demoboletto/repository/SysFrameRepository.java
- src/main/java/com/demoboletto/repository/UserCustomFrameRepository.java
- src/main/java/com/demoboletto/security/handler/logout/CustomLogoutProcessHandler.java
- src/main/java/com/demoboletto/service/ObjectStorageService.java
- src/main/java/com/demoboletto/service/TravelMemoryService.java
- src/main/java/com/demoboletto/service/TravelService.java
- src/main/java/com/demoboletto/service/UserFrameService.java
- src/main/java/com/demoboletto/type/EFrameType.java
- 유저가 업로드한 프레임을 사용할 수 있게 기능 추가
- #70 
<br/>
> [Feature] - 유저 업로드 프레임 관리
